// <auto-generated />
using System;
using Hourglass_CIS174_WesBrown.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hourglass_CIS174_WesBrown.Migrations
{
    [DbContext(typeof(HourglassDBContext))]
    [Migration("20191201021822_AddingPaidToWeeklyHours")]
    partial class AddingPaidToWeeklyHours
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hourglass_CIS174_WesBrown.Entity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<double>("PayRate");

                    b.Property<double>("RemainingPtoHours");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Hourglass_CIS174_WesBrown.Entity.PtoRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Approved");

                    b.Property<int>("EmployeeId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("RequestDate");

                    b.Property<double>("RequestedHours");

                    b.HasKey("Id");

                    b.ToTable("PtoRequests");
                });

            modelBuilder.Entity("Hourglass_CIS174_WesBrown.Entity.WeeklyHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId");

                    b.Property<bool>("IsDeleted");

                    b.Property<double>("OvertimeHours");

                    b.Property<bool>("Paid");

                    b.Property<double>("PtoHours");

                    b.Property<double>("RegularHours");

                    b.Property<double>("TotalHours");

                    b.Property<DateTime>("WeekEndtDate");

                    b.Property<DateTime>("WeekStartDate");

                    b.HasKey("Id");

                    b.ToTable("WeeklyHours");
                });
#pragma warning restore 612, 618
        }
    }
}
